name: publish-pages

# Run this workflow every time a new commit pushed to your repository
on:
    push:
        branches:
            - master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  publish-pages: 
    # Name the Job
    name: Build docs folder
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies 
        run: |
            yarn install --frozen-lockfile
            
      - name: Build pages  
        run: |
            yarn gulp
    
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: update docs file
            